title: Ernesto Gonzales
logo: /Profile_photo.png
description: I’m a bilingual data enthusiast. My interests are predictive analytics, business intelligence, machine learning, and how to apply them across domains. On a quest for professional growth and knowledge in the world of data. Welcome to my GitHub page.
show_downloads: False
theme: jekyll-theme-minimal
